/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacyScanRouteImport } from './routes/pharmacy.scan'
import { Route as LoginAdminRouteImport } from './routes/login_.admin'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyScanRoute = PharmacyScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => PharmacyRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login_/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient': typeof PatientRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/login/admin': typeof LoginAdminRoute
  '/pharmacy/scan': typeof PharmacyScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient': typeof PatientRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/login/admin': typeof LoginAdminRoute
  '/pharmacy/scan': typeof PharmacyScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient': typeof PatientRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/login_/admin': typeof LoginAdminRoute
  '/pharmacy/scan': typeof PharmacyScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/patient'
    | '/pharmacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/doctor/patients'
    | '/login/admin'
    | '/pharmacy/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/patient'
    | '/pharmacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/doctor/patients'
    | '/login/admin'
    | '/pharmacy/scan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/patient'
    | '/pharmacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/doctor/patients'
    | '/login_/admin'
    | '/pharmacy/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PatientRoute: typeof PatientRoute
  PharmacyRoute: typeof PharmacyRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  LoginAdminRoute: typeof LoginAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/scan': {
      id: '/pharmacy/scan'
      path: '/scan'
      fullPath: '/pharmacy/scan'
      preLoaderRoute: typeof PharmacyScanRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/login_/admin': {
      id: '/login_/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorRouteChildren {
  DoctorPatientsRoute: typeof DoctorPatientsRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorPatientsRoute: DoctorPatientsRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PharmacyRouteChildren {
  PharmacyScanRoute: typeof PharmacyScanRoute
}

const PharmacyRouteChildren: PharmacyRouteChildren = {
  PharmacyScanRoute: PharmacyScanRoute,
}

const PharmacyRouteWithChildren = PharmacyRoute._addFileChildren(
  PharmacyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DoctorRoute: DoctorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PatientRoute: PatientRoute,
  PharmacyRoute: PharmacyRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  LoginAdminRoute: LoginAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
