/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacyStockRouteImport } from './routes/pharmacy.stock'
import { Route as PharmacyScanRouteImport } from './routes/pharmacy.scan'
import { Route as PharmacyRequestsRouteImport } from './routes/pharmacy.requests'
import { Route as PharmacyPrescriptionsRouteImport } from './routes/pharmacy.prescriptions'
import { Route as PharmacyMessagesRouteImport } from './routes/pharmacy.messages'
import { Route as PharmacyMedicinesRouteImport } from './routes/pharmacy.medicines'
import { Route as PatientScanQrRouteImport } from './routes/patient.scan-qr'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientMessagesRouteImport } from './routes/patient.messages'
import { Route as PatientFindPharmacyRouteImport } from './routes/patient.find-pharmacy'
import { Route as PatientFindDoctorRouteImport } from './routes/patient.find-doctor'
import { Route as PatientAdherenceRouteImport } from './routes/patient.adherence'
import { Route as LoginAdminRouteImport } from './routes/login_.admin'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorPendingRouteImport } from './routes/doctor.pending'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorMessagesRouteImport } from './routes/doctor.messages'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyStockRoute = PharmacyStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyScanRoute = PharmacyScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyRequestsRoute = PharmacyRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyPrescriptionsRoute = PharmacyPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyMessagesRoute = PharmacyMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyMedicinesRoute = PharmacyMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => PharmacyRoute,
} as any)
const PatientScanQrRoute = PatientScanQrRouteImport.update({
  id: '/scan-qr',
  path: '/scan-qr',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMessagesRoute = PatientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientRoute,
} as any)
const PatientFindPharmacyRoute = PatientFindPharmacyRouteImport.update({
  id: '/find-pharmacy',
  path: '/find-pharmacy',
  getParentRoute: () => PatientRoute,
} as any)
const PatientFindDoctorRoute = PatientFindDoctorRouteImport.update({
  id: '/find-doctor',
  path: '/find-doctor',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAdherenceRoute = PatientAdherenceRouteImport.update({
  id: '/adherence',
  path: '/adherence',
  getParentRoute: () => PatientRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login_/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPendingRoute = DoctorPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorMessagesRoute = DoctorMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient': typeof PatientRouteWithChildren
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/pending': typeof DoctorPendingRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/login/admin': typeof LoginAdminRoute
  '/patient/adherence': typeof PatientAdherenceRoute
  '/patient/find-doctor': typeof PatientFindDoctorRoute
  '/patient/find-pharmacy': typeof PatientFindPharmacyRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/scan-qr': typeof PatientScanQrRoute
  '/pharmacy/medicines': typeof PharmacyMedicinesRoute
  '/pharmacy/messages': typeof PharmacyMessagesRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/pharmacy/requests': typeof PharmacyRequestsRoute
  '/pharmacy/scan': typeof PharmacyScanRoute
  '/pharmacy/stock': typeof PharmacyStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient': typeof PatientRouteWithChildren
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/pending': typeof DoctorPendingRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/login/admin': typeof LoginAdminRoute
  '/patient/adherence': typeof PatientAdherenceRoute
  '/patient/find-doctor': typeof PatientFindDoctorRoute
  '/patient/find-pharmacy': typeof PatientFindPharmacyRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/scan-qr': typeof PatientScanQrRoute
  '/pharmacy/medicines': typeof PharmacyMedicinesRoute
  '/pharmacy/messages': typeof PharmacyMessagesRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/pharmacy/requests': typeof PharmacyRequestsRoute
  '/pharmacy/scan': typeof PharmacyScanRoute
  '/pharmacy/stock': typeof PharmacyStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/patient': typeof PatientRouteWithChildren
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/pending': typeof DoctorPendingRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/login_/admin': typeof LoginAdminRoute
  '/patient/adherence': typeof PatientAdherenceRoute
  '/patient/find-doctor': typeof PatientFindDoctorRoute
  '/patient/find-pharmacy': typeof PatientFindPharmacyRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/scan-qr': typeof PatientScanQrRoute
  '/pharmacy/medicines': typeof PharmacyMedicinesRoute
  '/pharmacy/messages': typeof PharmacyMessagesRoute
  '/pharmacy/prescriptions': typeof PharmacyPrescriptionsRoute
  '/pharmacy/requests': typeof PharmacyRequestsRoute
  '/pharmacy/scan': typeof PharmacyScanRoute
  '/pharmacy/stock': typeof PharmacyStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/patient'
    | '/pharmacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/admin/users'
    | '/doctor/messages'
    | '/doctor/patients'
    | '/doctor/pending'
    | '/doctor/prescriptions'
    | '/login/admin'
    | '/patient/adherence'
    | '/patient/find-doctor'
    | '/patient/find-pharmacy'
    | '/patient/messages'
    | '/patient/prescriptions'
    | '/patient/scan-qr'
    | '/pharmacy/medicines'
    | '/pharmacy/messages'
    | '/pharmacy/prescriptions'
    | '/pharmacy/requests'
    | '/pharmacy/scan'
    | '/pharmacy/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/patient'
    | '/pharmacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/admin/users'
    | '/doctor/messages'
    | '/doctor/patients'
    | '/doctor/pending'
    | '/doctor/prescriptions'
    | '/login/admin'
    | '/patient/adherence'
    | '/patient/find-doctor'
    | '/patient/find-pharmacy'
    | '/patient/messages'
    | '/patient/prescriptions'
    | '/patient/scan-qr'
    | '/pharmacy/medicines'
    | '/pharmacy/messages'
    | '/pharmacy/prescriptions'
    | '/pharmacy/requests'
    | '/pharmacy/scan'
    | '/pharmacy/stock'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/patient'
    | '/pharmacy'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/admin/users'
    | '/doctor/messages'
    | '/doctor/patients'
    | '/doctor/pending'
    | '/doctor/prescriptions'
    | '/login_/admin'
    | '/patient/adherence'
    | '/patient/find-doctor'
    | '/patient/find-pharmacy'
    | '/patient/messages'
    | '/patient/prescriptions'
    | '/patient/scan-qr'
    | '/pharmacy/medicines'
    | '/pharmacy/messages'
    | '/pharmacy/prescriptions'
    | '/pharmacy/requests'
    | '/pharmacy/scan'
    | '/pharmacy/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PatientRoute: typeof PatientRouteWithChildren
  PharmacyRoute: typeof PharmacyRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  LoginAdminRoute: typeof LoginAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/stock': {
      id: '/pharmacy/stock'
      path: '/stock'
      fullPath: '/pharmacy/stock'
      preLoaderRoute: typeof PharmacyStockRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/scan': {
      id: '/pharmacy/scan'
      path: '/scan'
      fullPath: '/pharmacy/scan'
      preLoaderRoute: typeof PharmacyScanRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/requests': {
      id: '/pharmacy/requests'
      path: '/requests'
      fullPath: '/pharmacy/requests'
      preLoaderRoute: typeof PharmacyRequestsRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/prescriptions': {
      id: '/pharmacy/prescriptions'
      path: '/prescriptions'
      fullPath: '/pharmacy/prescriptions'
      preLoaderRoute: typeof PharmacyPrescriptionsRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/messages': {
      id: '/pharmacy/messages'
      path: '/messages'
      fullPath: '/pharmacy/messages'
      preLoaderRoute: typeof PharmacyMessagesRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/medicines': {
      id: '/pharmacy/medicines'
      path: '/medicines'
      fullPath: '/pharmacy/medicines'
      preLoaderRoute: typeof PharmacyMedicinesRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/patient/scan-qr': {
      id: '/patient/scan-qr'
      path: '/scan-qr'
      fullPath: '/patient/scan-qr'
      preLoaderRoute: typeof PatientScanQrRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/messages': {
      id: '/patient/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientMessagesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/find-pharmacy': {
      id: '/patient/find-pharmacy'
      path: '/find-pharmacy'
      fullPath: '/patient/find-pharmacy'
      preLoaderRoute: typeof PatientFindPharmacyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/find-doctor': {
      id: '/patient/find-doctor'
      path: '/find-doctor'
      fullPath: '/patient/find-doctor'
      preLoaderRoute: typeof PatientFindDoctorRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/adherence': {
      id: '/patient/adherence'
      path: '/adherence'
      fullPath: '/patient/adherence'
      preLoaderRoute: typeof PatientAdherenceRouteImport
      parentRoute: typeof PatientRoute
    }
    '/login_/admin': {
      id: '/login_/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/pending': {
      id: '/doctor/pending'
      path: '/pending'
      fullPath: '/doctor/pending'
      preLoaderRoute: typeof DoctorPendingRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/messages': {
      id: '/doctor/messages'
      path: '/messages'
      fullPath: '/doctor/messages'
      preLoaderRoute: typeof DoctorMessagesRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorMessagesRoute: typeof DoctorMessagesRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPendingRoute: typeof DoctorPendingRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorMessagesRoute: DoctorMessagesRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPendingRoute: DoctorPendingRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientAdherenceRoute: typeof PatientAdherenceRoute
  PatientFindDoctorRoute: typeof PatientFindDoctorRoute
  PatientFindPharmacyRoute: typeof PatientFindPharmacyRoute
  PatientMessagesRoute: typeof PatientMessagesRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientScanQrRoute: typeof PatientScanQrRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAdherenceRoute: PatientAdherenceRoute,
  PatientFindDoctorRoute: PatientFindDoctorRoute,
  PatientFindPharmacyRoute: PatientFindPharmacyRoute,
  PatientMessagesRoute: PatientMessagesRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientScanQrRoute: PatientScanQrRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PharmacyRouteChildren {
  PharmacyMedicinesRoute: typeof PharmacyMedicinesRoute
  PharmacyMessagesRoute: typeof PharmacyMessagesRoute
  PharmacyPrescriptionsRoute: typeof PharmacyPrescriptionsRoute
  PharmacyRequestsRoute: typeof PharmacyRequestsRoute
  PharmacyScanRoute: typeof PharmacyScanRoute
  PharmacyStockRoute: typeof PharmacyStockRoute
}

const PharmacyRouteChildren: PharmacyRouteChildren = {
  PharmacyMedicinesRoute: PharmacyMedicinesRoute,
  PharmacyMessagesRoute: PharmacyMessagesRoute,
  PharmacyPrescriptionsRoute: PharmacyPrescriptionsRoute,
  PharmacyRequestsRoute: PharmacyRequestsRoute,
  PharmacyScanRoute: PharmacyScanRoute,
  PharmacyStockRoute: PharmacyStockRoute,
}

const PharmacyRouteWithChildren = PharmacyRoute._addFileChildren(
  PharmacyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PatientRoute: PatientRouteWithChildren,
  PharmacyRoute: PharmacyRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  LoginAdminRoute: LoginAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
